import {db} from "./firebase.js";
import {collection,getDocs,query,where,addDoc,updateDoc,doc,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import {setupShell,esc,formatDate} from "./common.js";
let profile,all=[];
setupShell(null,async p=>{profile=p;document.getElementById("newAction").addEventListener("click",openModal);document.getElementById("closeAction").addEventListener("click",closeModal);document.getElementById("actionForm").addEventListener("submit",createAction);document.getElementById("statusFilter").addEventListener("change",render);document.getElementById("priorityFilter").addEventListener("change",render);if(profile.role==="franchisor")await populateOffices();await load();});
async function populateOffices(){const s=await getDocs(collection(db,"offices"));actionOffice.innerHTML=s.docs.map(d=>`<option value="${d.id}">${esc(d.data().name||d.id)}</option>`).join("");}
async function load(){let s=profile.role==="franchisor"?await getDocs(collection(db,"actions")):await getDocs(query(collection(db,"actions"),where("officeId","==",profile.officeId)));all=s.docs.map(d=>({id:d.id,...d.data()}));render();}
function render(){const st=statusFilter.value,pr=priorityFilter.value;let list=all.filter(a=>(st==="all"||a.status===st)&&(pr==="all"||a.priority===pr));list.sort((a,b)=>(a.dueDate||"9999").localeCompare(b.dueDate||"9999"));document.getElementById("actionList").innerHTML=list.length?list.map(a=>`<article class="action-card"><div class="action-main"><div class="action-title-row"><h3>${esc(a.title||"Action")}</h3><span class="priority ${esc(a.priority||"medium")}">${esc(a.priority||"medium")}</span></div><p>${esc(a.description||"No description provided.")}</p><div class="action-meta"><span>Due: ${esc(a.dueDate||"—")}</span><span>Office: ${esc(a.officeName||a.officeId||"—")}</span><span>Status: ${esc(a.status||"open")}</span></div></div>${a.status!=="completed"?`<button class="btn secondary small complete-action" data-id="${a.id}">Mark complete</button>`:'<span class="status good">Completed</span>'}</article>`).join(""):'<div class="empty-state">No actions match your filters.</div>';document.querySelectorAll(".complete-action").forEach(b=>b.addEventListener("click",()=>complete(b.dataset.id)));}
async function complete(id){await updateDoc(doc(db,"actions",id),{status:"completed",completedAt:serverTimestamp()});await load();}
function openModal(){document.getElementById("actionModal").classList.remove("hidden");if(profile.role==="franchisee")document.getElementById("officePickerWrap").classList.add("hidden");}
function closeModal(){document.getElementById("actionModal").classList.add("hidden");}
async function createAction(e){e.preventDefault();let officeId=profile.officeId,officeName="";if(profile.role==="franchisor"){officeId=actionOffice.value;const s=await getDocs(query(collection(db,"offices"),where("__name__","==",officeId)));officeName=s.empty?officeId:s.docs[0].data().name||officeId;}else{const s=await getDocs(query(collection(db,"offices"),where("__name__","==",officeId)));officeName=s.empty?officeId:s.docs[0].data().name||officeId;}
await addDoc(collection(db,"actions"),{title:actionTitle.value.trim(),description:actionDescription.value.trim(),dueDate:actionDueDate.value||"",priority:actionPriority.value,status:"open",officeId,officeName,createdAt:serverTimestamp(),createdBy:profile.uid});document.getElementById("actionForm").reset();closeModal();await load();}
