import {db} from "./firebase.js";
import {collection,getDocs,query,where,addDoc,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import {setupShell,esc,formatDate} from "./common.js";
let profile,all=[];
setupShell(null,async p=>{profile=p;newEvidence.onclick=openModal;closeEvidence.onclick=closeModal;evidenceForm.addEventListener("submit",save);if(profile.role==="franchisor")await offices();await load();});
async function offices(){const s=await getDocs(collection(db,"offices"));evidenceOffice.innerHTML=s.docs.map(d=>`<option value="${d.id}">${esc(d.data().name||d.id)}</option>`).join("");}
async function load(){let s=profile.role==="franchisor"?await getDocs(collection(db,"evidence")):await getDocs(query(collection(db,"evidence"),where("officeId","==",profile.officeId)));all=s.docs.map(d=>({id:d.id,...d.data()}));evidenceList.innerHTML=all.length?all.map(x=>`<article class="evidence-card"><div class="evidence-icon">▣</div><div><p class="eyebrow">${esc(x.category||"OTHER")}</p><h3>${esc(x.title||"Evidence")}</h3><p>${esc(x.reference||"No reference supplied.")}</p><small>${esc(x.officeName||x.officeId||"Network")} · Added ${formatDate(x.createdAt)}</small>${x.notes?`<div class="note">${esc(x.notes)}</div>`:""}</div></article>`).join(""):'<div class="empty-state">No evidence records have been added yet.</div>';}
function openModal(){evidenceModal.classList.remove("hidden")}function closeModal(){evidenceModal.classList.add("hidden")}
async function save(e){e.preventDefault();let officeId=profile.officeId,officeName="";if(profile.role==="franchisor"){officeId=evidenceOffice.value;const o=await getDocs(query(collection(db,"offices"),where("__name__","==",officeId)));officeName=o.empty?officeId:o.docs[0].data().name||officeId}else{const o=await getDocs(query(collection(db,"offices"),where("__name__","==",officeId)));officeName=o.empty?officeId:o.docs[0].data().name||officeId}
await addDoc(collection(db,"evidence"),{title:evidenceTitle.value.trim(),category:evidenceCategory.value,reference:evidenceReference.value.trim(),notes:evidenceNotes.value.trim(),officeId,officeName,createdAt:serverTimestamp(),createdBy:profile.uid});evidenceForm.reset();closeModal();await load();}
