import {db} from "./firebase.js";
import {collection,getDocs,setDoc,doc,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import {setupShell,esc,scoreStatus} from "./common.js?v=20260811-ho-staff-v2";
let offices=[];
setupShell("franchisor",async()=>{newOffice.onclick=()=>open();closeOffice.onclick=close;officeForm.addEventListener("submit",save);await load();});
async function load(){const s=await getDocs(collection(db,"offices"));offices=s.docs.map(d=>({id:d.id,...d.data()}));officeGrid.innerHTML=offices.map(o=>`<article class="office-card"><div class="office-card-top"><div class="office-icon">⌂</div>${scoreStatus(o.complianceScore)}</div><h3>${esc(o.name||o.id)}</h3><p>${esc(o.location||"Location not set")}</p><div class="office-mini"><span>Overall<strong>${o.complianceScore??0}%</strong></span><span>Audits<strong>${o.auditCompletion??0}%</strong></span><span>Actions<strong>${o.openActions??0}</strong></span></div><button class="btn secondary small edit-office" data-id="${o.id}">Edit office</button></article>`).join("")||'<div class="empty-state">No offices have been added.</div>';document.querySelectorAll(".edit-office").forEach(b=>b.onclick=()=>open(b.dataset.id));}
function open(id=null){officeModal.classList.remove("hidden");officeForm.reset();officeId.disabled=!!id;officeModalTitle.textContent=id?"Edit office":"Add office";if(id){const o=offices.find(x=>x.id===id);officeId.value=id;officeName.value=o.name||"";officeLocation.value=o.location||"";officeScore.value=o.complianceScore||0;officeAudit.value=o.auditCompletion||0;scoreDocumentation.value=o.scores?.documentation||0;scoreStaff.value=o.scores?.staff||0;scoreCompliance.value=o.scores?.compliance||0;scoreMarketing.value=o.scores?.marketing||0;}}
function close(){officeModal.classList.add("hidden")}
async function save(e){e.preventDefault();const id=officeId.value.trim().toLowerCase().replace(/\s+/g,"-");await setDoc(doc(db,"offices",id),{name:officeName.value.trim(),location:officeLocation.value.trim(),complianceScore:Number(officeScore.value),auditCompletion:Number(officeAudit.value),openActions:0,scores:{documentation:Number(scoreDocumentation.value),staff:Number(scoreStaff.value),compliance:Number(scoreCompliance.value),marketing:Number(scoreMarketing.value)},active:true,updatedAt:serverTimestamp()},{merge:true});close();await load();}
